module.exports = [
    {name: "CANodeProfileNone", id: 0, accessory: ""},
    {name: "CANodeProfileHomee", id: 1, accessory: ""},

    // Generic (10-999)
    {name: "CANodeProfileOnOffPlug", id: 10, accessory: ""},
    {name: "CANodeProfileDimmableMeteringSwitch", id: 11, accessory: ""},
    {name: "CANodeProfileMeteringSwitch", id: 12, accessory: ""},
    {name: "CANodeProfileMeteringPlug", id: 13, accessory: ""},
    {name: "CANodeProfileDimmablePlug", id: 14, accessory: ""},
    {name: "CANodeProfileDimmableSwitch", id: 15, accessory: ""},
    {name: "CANodeProfileOnOffSwitch", id: 16, accessory: ""},
    {name: "CANodeProfileDoubleOnOffSwitch", id: 18, accessory: ""},
    {name: "CANodeProfileDimmableMeteringPlug", id: 19, accessory: ""},
    {name: "CANodeProfileOneButtonRemote", id: 20, accessory: ""},
    {name: "CANodeProfileBinaryInput", id: 21, accessory: ""},
    {name: "CANodeProfileDimmableColorMeteringSwitch", id: 22, accessory: ""},
    {name: "CANodeProfileDoubleBinaryInput", id: 23, accessory: ""},
    {name: "CANodeProfileTwoButtonRemote", id: 24, accessory: ""},
    {name: "CANodeProfileThreeButtonRemote", id: 25, accessory: ""},
    {name: "CANodeProfileFourButtonRemote", id: 26, accessory: ""},
    {name: "CANodeProfileAlarmSensor", id: 27, accessory: ""},
    {name: "CANodeProfileDoubleOnOffPlug", id: 28, accessory: ""},
    {name: "CANodeProfileOnOffSwitchWithBinaryInput", id: 29, accessory: ""},
    {name: "CANodeProfileWatchDogWithManyTemperatures", id: 30, accessory: ""},

    // Lighting (1000-1999)
    {name: "CANodeProfileBrightnessSensor", id: 1000, accessory: ""},
    {name: "CANodeProfileDimmableColorLight", id: 1001, accessory: ""},
    {name: "CANodeProfileDimmableExtendedColorLight", id: 1002, accessory: ""},
    {name: "CANodeProfileDimmableColorTemperatureLight", id: 1003, accessory: ""},
    {name: "CANodeProfileDimmableLight", id: 1004, accessory: ""},
    {name: "CANodeProfileDimmableLightWithBrightnessSensor", id: 1005, accessory: ""},
    {name: "CANodeProfileDimmableLightWithBrightnessAndPresenceSensor", id: 1006, accessory: ""},
    {name: "CANodeProfileDimmableLightWithPresenceSensor", id: 1007, accessory: ""},
    {name: "CANodeProfileDimmableRGBWLight", id: 1008, accessory: ""},

    // Closures (2000-2999)
    {name: "CANodeProfileOpenCloseSensor", id: 2000, accessory: "ContactSensor"},
    {name: "CANodeProfileWindowHandle", id: 2001, accessory: ""},
    {name: "CANodeProfileShutterPositionSwitch", id: 2002, accessory: ""},
    {name: "CANodeProfileOpenCloseAndTemperatureSensor", id: 2003, accessory: ""},
    {name: "CANodeProfileElectricMotorMeteringSwitch", id: 2004, accessory: ""},
    {name: "CANodeProfileOpenCloseWithTemperatureAndBrightnessSensor", id: 2005, accessory: "ContactSensor"},
    {name: "CANodeProfileElectricMotorMeteringSwitchWithoutSlatPosition", id: 2006, accessory: ""},

    // HVAC (3000-3999)
    {name: "CANodeProfileTemperatureAndHumiditySensor", id: 3001, accessory: ""},
    {name: "CANodeProfileCO2Sensor", id: 3002, accessory: ""},
    {name: "CANodeProfileRoomThermostat", id: 3003, accessory: ""},
    {name: "CANodeProfileRoomThermostatWithHumiditySensor", id: 3004, accessory: ""},
    {name: "CANodeProfileBinaryInputWithTemperatureSensor", id: 3005, accessory: ""},
    {name: "CANodeProfileRadiatorThermostat", id: 3006, accessory: "Thermostat"},
    {name: "CANodeProfileTemperatureSensor", id: 3009, accessory: ""},
    {name: "CANodeProfileHumiditySensor", id: 3010, accessory: ""},
    {name: "CANodeProfileWaterValve", id: 3011, accessory: ""},
    {name: "CANodeProfileWaterMeter", id: 3012, accessory: ""},
    {name: "CANodeProfileWeatherStation", id: 3013, accessory: ""},
    {name: "CANodeProfileNetatmoMainModule", id: 3014, accessory: ""},
    {name: "CANodeProfileNetatmoOutdoorModule", id: 3015, accessory: ""},
    {name: "CANodeProfileNetatmoIndoorModule", id: 3016, accessory: ""},
    {name: "CANodeProfileNetatmoRainModule", id: 3017, accessory: ""},
    {name: "CANodeProfileTwoChannelCosiTherm", id: 3018, accessory: ""},
    {name: "CANodeProfileSixChannelCosiTherm", id: 3019, accessory: ""},
    {name: "CANodeProfileNestThermostatWithCooling", id: 3020, accessory: ""},
    {name: "CANodeProfileNestThermostatWithHeating", id: 3021, accessory: ""},
    {name: "CANodeProfileNestThermostatWithHeatingAndCooling", id: 3022, accessory: ""},
    {name: "CANodeProfileNetatmoWindModule", id: 3023, accessory: ""},
    {name: "CANodeProfileElectricalHeating", id: 3024, accessory: ""},
    {name: "CANodeProfileValveDrive", id: 3025, accessory: ""},
    {name: "CANodeProfileNetatmoCamera", id: 3026, accessory: ""},
    {name: "CANodeProfileNetatmoThermostat", id: 3027, accessory: ""},
    {name: "CANodeProfileNetatmoTags", id: 3028, accessory: ""},

    // Alarm (4000-4999)
    {name: "CANodeProfileMotionDetectorWithTemperatureBrightnessAndHumiditySensor", id: 4010, accessory: ""},
    {name: "CANodeProfileMotionDetector", id: 4011, accessory: "MotionSensor"},
    {name: "CANodeProfileSmokeDetector", id: 4012, accessory: ""},
    {name: "CANodeProfileFloodDetector", id: 4013, accessory: ""},
    {name: "CANodeProfilePresenceDetector", id: 4014, accessory: ""},
    {name: "CANodeProfileMotionDetectorWithTemperatureAndBrightnessSensor", id: 4015, accessory: "MotionSensor"},
    {name: "CANodeProfileSmokeDetectorWithTemperatureSensor", id: 4016, accessory: ""},
    {name: "CANodeProfileFloodDetectorWithTemperatureSensor", id: 4017, accessory: ""},
    {name: "CANodeProfileWatchDogDevice", id: 4018, accessory: ""},
    {name: "CANodeProfileLAG", id: 4019, accessory: ""},
    {name: "CANodeProfileOWU", id: 4020, accessory: ""},
    {name: "CANodeProfileEurovac", id: 4021, accessory: ""},
    {name: "CANodeProfileOWWG3", id: 4022, accessory: ""},
    {name: "CANodeProfileEuropress", id: 4023, accessory: ""},
    {name: "CANodeProfileMinimumDetector", id: 4024, accessory: ""},
    {name: "CANodeProfileMaximumDetector", id: 4025, accessory: ""},
    {name: "CANodeProfileSmokeDetectorAndCODetector", id: 4026, accessory: ""},
    {name: "CANodeProfileSiren", id: 4027, accessory: ""},
    {name: "CANodeProfileMotionDetectorWithOpenCloseTemperatureAndBrightnessSensor", id: 4028, accessory: ""},
    {name: "CANodeProfileMotionDetectorWithBrightness", id: 4029, accessory: ""},
    {name: "CANodeProfileDoorbell", id: 4030, accessory: ""},
    {name: "CANodeProfileSmokeDetectorAndSiren", id: 4031, accessory: ""},
    {name: "CANodeProfileFloodDetectorWithTemperatureAndHumiditySensor", id: 4032, accessory: ""},

    // Hager (5000-5999)
    {name: "CANodeProfileInovaAlarmSystem", id: 5000, accessory: ""},
    {name: "CANodeProfileInovaDetector", id: 5001, accessory: ""},
    {name: "CANodeProfileInovaSiren", id: 5002, accessory: ""},
    {name: "CANodeProfileInovaCommand", id: 5003, accessory: ""},
    {name: "CANodeProfileInovaTransmitter", id: 5004, accessory: ""},
    {name: "CANodeProfileInovaReciever", id: 5005, accessory: ""},
    {name: "CANodeProfileInovaKoala", id: 5006, accessory: ""},
    {name: "CANodeProfileInovaInternalTransmitter", id: 5007, accessory: ""},
    {name: "CANodeProfileInovaControlPanel", id: 5008, accessory: ""},
    {name: "CANodeProfileInovaInputOutputExtension", id: 5009, accessory: ""},
    {name: "CANodeProfileInovaMotionDetectorWithVOD", id: 5010, accessory: ""},
    {name: "CANodeProfileInovaMotionDetector", id: 5011, accessory: ""},

    // Plants (6000-6999)
    {name: "CANodeProfileKoubachiPlantSensor", id: 6000, accessory: ""}
]
